### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by kasmacioma** [BloomCreativeWorks/BloomFramework#7]
**Questions:**
 - what about using ```unordered_map``` instead of ```map``` (as ```unordered_map``` seems faster then ```map```)
 - what about using ```*&``` for ```SDL_Renderer``` in Texture class instead of ```**```
 - maybe you should use the global texture store (to store textures of all Game objects)

**Comment by LumpBloom7** [comment]
Maybe I could use `unordered_map`

Because I had a little trouble with pointers I've changed it to `**` and forgot to change it back. My mistake there.

Each `TextureStore` should be associated with a `Game` object since it relies on it's renderer.

**Comment by LumpBloom7** [comment]
Wow the performance difference is huge for the first case!

I'd be damned if I don't take advantage.

**Comment by LumpBloom7** [comment]
I should be able to fix up this issue tomorrow after school.

**Comment by LumpBloom7** [comment]
Resolved in #8
